# Copyright (c) 2018 Simply Code Ltd. All rights reserved.
# Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

sudo: required
dist: xenial
language: csharp
solution: PackIt.sln

addons:
  sonarcloud:
    organization: simplycodeuk

mono:
  - latest
  - 5.18.0

dotnet: 2.2

env:
  - CONFIG=Debug
  - CONFIG=Release

before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.12.*

cache:
  yarn: yes

install:
  - nuget restore PackIt.sln
  - dotnet restore PackIt.sln

script:
  - sonar-scanner
  - msbuild /p:Configuration=$CONFIG /t:rebuild PackIt.sln
  - dotnet pack PackItLib/src/PackItLib.csproj --configuration $CONFIG
  - dotnet test PackItLib/test/PackItLib.Test.csproj --configuration $CONFIG --logger:trx
  - dotnet test PackIt/test/PackIt.Test.csproj --configuration $CONFIG --logger:trx
  - dotnet test PackItUI/test/PackItUI.Test.csproj --configuration $CONFIG --logger:trx

notifications:
  slack: simplycodeuk:FZI8WzeengkGv5LI7WQSCrJs
