# Copyright (c) 2018-2020 Simply Code Ltd. All rights reserved.
# Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

sudo: required
dist: xenial
language: csharp
solution: PackIt.sln

addons:
  sonarcloud:
    organization: simplycodeuk

mono:
  - latest
  - 6.6.0

dotnet: 3.1

env:
  global:
    - ASPNETCORE_ENVIRONMENT=Development
    - DOTNET_PRINT_TELEMETRY_MESSAGE=false
    - DOTNET_CLI_TELEMETRY_OPTOUT=true
  matrix:
    - CONFIG=Release
    - CONFIG=Debug

before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.12.*

cache:
  yarn: yes

install:
  - nuget restore PackIt.sln
  - dotnet --version
  - dotnet restore PackIt.sln

script:
  - sonar-scanner
  - dotnet build PackItLib/src/PackItLib.csproj       --configuration $CONFIG
  - dotnet build PackItLib/test/PackItLib.Test.csproj --configuration $CONFIG
  - dotnet build PackIt/src/PackIt.csproj             --configuration $CONFIG
  - dotnet build PackIt/test/PackIt.Test.csproj       --configuration $CONFIG
  - dotnet build PackItUI/src/PackItUI.csproj         --configuration $CONFIG
  - dotnet build PackItUI/test/PackItUI.Test.csproj   --configuration $CONFIG
  - dotnet pack PackItLib/src/PackItLib.csproj        --configuration $CONFIG
  - dotnet test PackItLib/test/PackItLib.Test.csproj  --configuration $CONFIG --logger:trx
  - dotnet test PackIt/test/PackIt.Test.csproj        --configuration $CONFIG --logger:trx
  - dotnet test PackItUI/test/PackItUI.Test.csproj    --configuration $CONFIG --logger:trx

notifications:
  slack: simplycodeuk:FZI8WzeengkGv5LI7WQSCrJs
