# Copyright (c) 2018 Simply Code Ltd. All rights reserved.
# Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

sudo: required
dist: trusty
language: csharp
solution: PackIt.sln

mono:
  - latest
  - 5.10.0

dotnet: 2.0.0

env:
  - CONFIG=Debug
  - CONFIG=Release

install:
  - nuget restore PackIt.sln
  - dotnet restore PackIt.sln

script:
  - msbuild /p:Configuration=$CONFIG /t:rebuild PackIt.sln
  - dotnet pack PackItLib/src/PackItLib/PackItLib.csproj --configuration $CONFIG
  - dotnet test PackIt/test/PackIt.Test/PackIt.Test.csproj --configuration $CONFIG --logger:trx
  - dotnet test PackItLib/test/PackItLib.Test/PackItLib.Test.csproj --configuration $CONFIG --logger:trx

notifications:
  slack: simplycodeuk:FZI8WzeengkGv5LI7WQSCrJs
