sudo: required
dist: trusty
language: csharp
solution: packer-strategy.sln

mono:
  - latest
  - 5.2.0

dotnet: 2.0.0

env:
  - CONFIG=Debug
  - CONFIG=Release

install:
  - nuget restore packer-strategy.sln
  - dotnet restore packer-strategy.sln

script:
  - msbuild /p:Configuration=$CONFIG /t:rebuild packer-strategy.sln
  - dotnet test packer-strategy-test/packer-strategy-test.csproj --configuration $CONFIG --no-build --logger:trx
  - dotnet pack packer-strategy.sln --configuration $CONFIG

notifications:
  slack: simplycodeuk:FZI8WzeengkGv5LI7WQSCrJs
