sudo: required
dist: trusty
language: csharp
solution: PackIt.sln

mono:
  - latest
  - 5.2.0

dotnet: 2.0.0

env:
  - CONFIG=Debug
  - CONFIG=Release

install:
  - nuget restore PackIt.sln
  - dotnet restore PackIt.sln

script:
  - msbuild /p:Configuration=$CONFIG /t:rebuild PackIt.sln
  - dotnet test PackItTest/PackItTest.csproj --configuration $CONFIG --no-build --logger:trx
  - dotnet pack PackIt/PackIt.csproj --configuration $CONFIG

notifications:
  slack: simplycodeuk:FZI8WzeengkGv5LI7WQSCrJs
