 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default

     steps:
       - checkout
       - run:
           name: "Build solution"
           command: dotnet build /p:DocumentationFile=codedoc.xml
       - run:
           name: "Pack the solution"
           command: dotnet pack
       - run:
           name: "Test solution"
           command: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:ExcludeFromCoverage="**/*.cshtml" --logger:trx --results-directory:test_coverage --collect:"Code Coverage"
       - run:
           name: "Publish the solution"
           command: dotnet publish
       - store_artifacts:
           path: ./test_coverage
