version: 2.1

workflows:
  version: 2
  build-test-and-publish:
    jobs:
      - build:
          matrix:
            parameters:
              config: ["Debug", "Release"]

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    parameters:
      config:
        default: "Debug"
        type: string
    executor: win/default
    steps:
      - checkout
      - run:
          name: "Nuget Restore"
          command: nuget restore PackIt.sln
      - run:
          name: "dotnet version"
          command: dotnet --version
      - run:
          name: "Restore solution"
          command: dotnet restore PackIt.sln
      - run:
          name: "Build solution"
          command: dotnet build PackIt.sln -c << parameters.config >> /p:DocumentationFile=codedoc.xml
      - run:
          name: "Pack the solution"
          command: dotnet pack PackIt.sln -c << parameters.config >> 
      - run:
          name: "Test PackItLib"
          command: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:ExcludeFromCoverage="**/*.cshtml" PackItLib/test/PackItLib.Test.csproj   -c << parameters.config >> --logger:trx
      - run:
          name: "Test PackIt"
          command: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:ExcludeFromCoverage="**/*.cshtml" PackIt/test/PackIt.Test.csproj         -c << parameters.config >> --logger:trx
      - run:
          name: "Test PackItDraw"
          command: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:ExcludeFromCoverage="**/*.cshtml" PackItDraw/test/PackItDraw.Test.csproj -c << parameters.config >> --logger:trx
      - run:
          name: "Test PackItUI"
          command: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:ExcludeFromCoverage="**/*.cshtml" PackItUI/test/PackItUI.Test.csproj     -c << parameters.config >> --logger:trx
      - store_test_results:
          path: ./test_coverage
      - store_artifacts:
          path: ./test_coverage
      - run:
          name: "Publish the solution"
          command: dotnet publish PackIt.sln -c << parameters.config >>
