version: 2.1

workflows:
  version: 2.1
  build-test-and-publish:
    jobs:
      - build:
          matrix:
            parameters:
              config: ["Debug", "Release"]
      - test:
          requires:
            - build
      - publish:
          requires:
            - test

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    parameters:
      config:
        default: "Debug"
        type: string
    executor: win/default
    steps:
      - checkout
      - run:
          name: "Build solution"
          command: dotnet build --configuration << parameters.config >> /p:DocumentationFile=codedoc.xml
      - run:
          name: "Pack the solution"
          command: dotnet pack --configuration << parameters.config >> 
  test:
    parameters:
      config:
        default: "Debug"
        type: string
    executor: win/default
    steps:
      - run:
          name: "Test solution"
          command: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:ExcludeFromCoverage="**/*.cshtml" --logger:trx --configuration << parameters.config >> --results-directory:test_coverage --collect:"Code Coverage"
      - store_artifacts:
          path: ./test_coverage
  publish:
    parameters:
      config:
        default: "Debug"
        type: string
    executor: win/default
    steps:
      - run:
          name: "Publish the solution"
          command: dotnet publish --configuration << parameters.config >>
