name: code-quality

on: [push, pull_request]

jobs:
  code-quality:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        language: ['csharp']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set .NET version to use
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.102'
      - name: Set Node version to use
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      - name: Restore
        run: |
          nuget restore PackIt.sln
          dotnet restore PackIt.sln
      - name: Build
        run: |
          dotnet build -c Release
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
